export const GET_DROPDOWN_ITEMS = "GET_DROPDOWN_ITEMS";
export const GET_HOC_DROPDOWN_ITEMS = "GET_HOC_DROPDOWN_ITEMS";
export const GET_RP_DROPDOWN_ITEMS = "GET_RP_DROPDOWN_ITEMS";
export const RESET_DROPDOWN_ITEMS = "RESET_DROPDOWN_ITEMS";
export const RESET_HOC_DROPDOWN_ITEMS = "RESET_HOC_DROPDOWN_ITEMS";
export const RESET_RP_DROPDOWN_ITEMS = "RESET_RP_DROPDOWN_ITEMS";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
